package:
  name: opengm
  version: 0.1.0

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - cmake>=3.1
    - conda-forge::xtl
    - conda-forge::xtensor
    - python>=3.6
    - numpy>=1.16
    - conda-forge::pybind11
    - conda-forge::xtensor-python
    
  run:
    - numpy>=1.16
    - python>=3.6
    
test:
  requires:
    - pytest
  imports:
    - opengm
  
  commands:
    - test -d ${PREFIX}/include/opengm           # [unix]
    - test -f ${PREFIX}/include/opengm/opengm.hpp # [unix]
    - if exist %LIBRARY_PREFIX%\include\opengm\opengm.hpp (exit 0) else (exit 1)  # [win]
    # - make cpp-test
    # -  make python-test

about:
  home:  https://github.com/DerThorsten/opengm
  license: MIT
  license_family: MIT
  
  summary: 'opengm is a modern C++ library'
  description: 'opengm is a modern C++ library'
  documentation_url: https://readthedocs.org/projects/opengm/
  dev_url: https://github.com/DerThorsten/opengm

extra:
  recipe-maintainers:
    - Thorsten Beier

